export {
  SCHEDULE_CATEGORIES,
  REQUIRED_CATEGORIES,
  KONFIGURASI_EQUIVALENT_CATEGORIES,
  REVIEW_TRIGGER_CATEGORIES,
  INCENTIVE_TRIGGER_CATEGORIES,
  CONTROLLER_CATEGORIES,
  SCHEDULE_STATUSES,
  SCHEDULE_STATUS_LABELS,
  SCHEDULE_STATUS_COLORS,
  isKonfigurasiBehavior,
  requiresController,
} from '@/lib/constants/categories';
